spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/storageapp
    username: postgres
    password: alex
    driver-class-name: org.postgresql.Driver
    springdoc:
      show-actuator: false
      swagger-ui:
        enabled: true
        path: /swagger-ui.html
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
